### ISSUE TITLE
thanks!

### ISSUE THREAD

**Issue by matthlavacka** [ahakem/react-lazyload-youtube#2]
thanks @ahakem, all the packages I tried were huge and this one is super lightweight. 

I changed it a to not use `<img>`, but a `background-image` so the image can be without black lines on top and bottom.

```js
const YoutubeLazy = ({videoId, width, height}) => {
  const [showVideo, setShowVideo] = useState(false);
  return (
    <>
      {showVideo ? (
        <iframe
          title="youtube-lazy"
          width={width || '100%'}
          height={height || '400px'}
          src={`https://www.youtube.com/embed/${videoId}?autoplay=1&showinfo=0`}
          frameBorder="0"
          allowFullScreen
          />
      ) : (
        <div className={cx('image')} style={{backgroundImage: `url(${`https://img.youtube.com/vi/${videoId}/sddefault.jpg`})`, width, height}} onClick={() => setShowVideo(true)}>
          <div className={cx('play-button')} />
        </div>
      )}
    </>
  );
};

export default YoutubeLazy;
```

and 

```css
.image{
  position: relative;
  display: inline-block;
  background-position: center;
  background-size: cover;
  background-repeat: no-repeat;
  background-color: #fff;
  cursor: pointer;
}

.image:hover .play-button{
  background-color: #FF0000;
}

.play-button {
  cursor: pointer;
  position: absolute;
  left: 0;
  top: 0;
  bottom: 0;
  right: 0;
  margin: auto;
  height: 50px;
  width: 80px;
  background-color: rgba(0, 0, 0, 0.7);
  border-radius: 8px;
  z-index: 5;
}

.play-button:after {
  content: "";
  display: block;
  position: absolute;
  top: 13.5px;
  left: 32px;
  margin: 0 auto;
  border-style: solid;
  border-width: 12.5px 0 12.5px 20px;
  border-color: transparent transparent transparent rgba(255, 255, 255, 1);
}
```

In case you want to show live example in readme, I added it on my production project here - https://databaselog.com/#how-it-works

Cheers
